### ISSUE TITLE
Shortcuts not working on Linux

### ISSUE THREAD

**Issue by chk-mue-lab** [vc-devel/vcGiftTrac#14]
The shortcuts on Linux are META-x. They are not usable like that since the META key is used for other purposes.
I guess the solution could be to redefine the shortcuts on MAC from **ctrl** to **cmd**. That way on linux **ctrl** is used instead of **META**.

**Comment by chkmue** [comment]
Solved with commit 74900fd6d4a9b3fa70a0c9e5fa12d670bf0a08bd
